image: node:6

cache:
  paths:
    - /home/forge/dev.cjarellano.com/wp-content/themes/cjarellano/node_modules/

stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - cd /home/forge/dev.cjarellano.com
    - git pull
    - cd wp-content/themes/cjarellano
    - npm install
    - npm run production
  environment:
    name: dev
    url: https://dev.cjarellano.com
  only:
  - develop

