image: node:6

stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - cd /home/forge/dev.cjarellano.com
    - git pull
    - cd wp-content/themes/cjarellano
    - npm install
    - npm run production
  environment:
    name: dev
    url: https://dev.cjarellano.com
  only:
  - develop

deploy_prod:
  stage: deploy
  script:
    - cd /home/forge/cjarellano.com
    - git pull
    - cd wp-content/themes/cjarellano
    - npm install
    - npm run production
  environment:
    name: prod
    url: https://cjarellano.com
  only:
  - master
